name: PR Notification Workflow
on:
  schedule:
    - cron: '0 9 * * MON-FRI'
  workflow_dispatch:
jobs:
  notify-about-open-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: aleksei-bulgak/pr-reviews-reminder-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: ${{ secrets.SLACK_WEBHOOK }} #https://hooks.slack.com/services/<channel-specific-part-of-the-path>
        channel: ${{ secrets.SLACK_CHANNEL_NAME }} #testnotifications
        github-provider-map: |
          aleksei-bulgak-study:U30U43YTU,
          aleksei-bulgak:U02Q8QJHDD3