name: Simple PR Notification Workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_PATH: ${{ secrets.SLACK_WEBHOOK_PATH }}
        GITHUB2SLACK_MAPPING: ${{ secrets.GITHUB2SLACK_MAPPING }}
      with:
        webhook-url: 'https://hooks.slack.com/services/$env:SLACK_WEBHOOK_PATH'
        provider: 'slack'
        channel: 'testnotifications'
        github-provider-map: '$env:GITHUB2SLACK_MAPPING'